export const translates = {
  en: {
    speakNow: "Speak now",
    noSpeech: "No speech detected.",
    audioCapture: "Audio capture problem.",
    enableMicrophone: "Enable the microphone",
    close: "Close voice capture",
    open: "Start voice capture",
  },
  pt: {
    speakNow: "Fale agora",
    noSpeech: "Nenhuma fala detectada.",
    audioCapture: "Problema na captura de áudio.",
    enableMicrophone: "Ative o microfone",
    close: "Fechar captura de voz",
    open: "Iniciar captura de voz",
  },
  es: {
    speakNow: "Habla ahora",
    noSpeech: "No se detectó voz.",
    audioCapture: "Problema en la captura de audio.",
    enableMicrophone: "Activa el micrófono",
    close: "Cerrar captura de voz",
    open: "Iniciar captura de voz",
  },
  fr: {
    speakNow: "Parlez maintenant",
    noSpeech: "Aucune parole détectée.",
    audioCapture: "Problème de capture audio.",
    enableMicrophone: "Activez le microphone",
    close: "Fermer la capture vocale",
    open: "Démarrer la capture vocale",
  },
  de: {
    speakNow: "Sprich jetzt",
    noSpeech: "Keine Sprache erkannt.",
    audioCapture: "Audioproblem.",
    enableMicrophone: "Aktivieren Sie das Mikrofon",
    close: "Spracherfassung schließen",
    open: "Spracherfassung starten",
  },
  it: {
    speakNow: "Parla ora",
    noSpeech: "Nessuna parola rilevata.",
    audioCapture: "Problema con la cattura audio.",
    enableMicrophone: "Abilita il microfono",
    close: "Chiudere la cattura vocale",
    open: "Avviare la cattura vocale",
  },
  ja: {
    speakNow: "今話してください",
    noSpeech: "音声が検出されませんでした。",
    audioCapture: "オーディオキャプチャの問題。",
    enableMicrophone: "マイクを有効にしてください",
    close: "音声キャプチャを閉じる",
    open: "音声キャプチャを開始",
  },
  zh: {
    speakNow: "现在说话",
    noSpeech: "没有检测到语音。",
    audioCapture: "音频捕获问题。",
    enableMicrophone: "启用麦克风",
    close: "关闭语音捕捉",
    open: "开始语音捕捉",
  },
  ru: {
    speakNow: "Говорите сейчас",
    noSpeech: "Речь не обнаружена.",
    audioCapture: "Проблема с захватом звука.",
    enableMicrophone: "Включите микрофон",
    close: "Закрыть захват голоса",
    open: "Начать захват голоса",
  },
  ar: {
    speakNow: "تحدث الآن",
    noSpeech: "لم يتم اكتشاف الكلام.",
    audioCapture: "مشكلة في التقاط الصوت.",
    enableMicrophone: "قم بتمكين الميكروفون",
    close: "إغلاق التقاط الصوت",
    open: "بدء التقاط الصوت",
  },
  ko: {
    speakNow: "지금 말하세요",
    noSpeech: "음성이 감지되지 않았습니다.",
    audioCapture: "오디오 캡처 문제.",
    enableMicrophone: "마이크를 활성화하세요",
    close: "음성 캡처 닫기",
    open: "음성 캡처 시작",
  },
  nl: {
    speakNow: "Spreek nu",
    noSpeech: "Geen spraak gedetecteerd.",
    audioCapture: "Probleem met audiovangst.",
    enableMicrophone: "Activeer de microfoon",
    close: "Stemopname sluiten",
    open: "Stemopname starten",
  },
  sv: {
    speakNow: "Tala nu",
    noSpeech: "Ingen tal upptäckt.",
    audioCapture: "Problem med ljudinspelning.",
    enableMicrophone: "Aktivera mikrofonen",
    close: "Stäng röstinspelning",
    open: "Starta röstinspelning",
  },
};
